# Generated by Django 2.1.2 on 2018-11-15 19:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('url', models.TextField(blank=True)),
                ('pub_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('votes_total', models.IntegerField(blank=True, null=True)),
                ('product_pic', versatileimagefield.fields.VersatileImageField(height_field='150', upload_to='product_pics/', width_field='150')),
                ('icon_pic', versatileimagefield.fields.VersatileImageField(height_field='50', upload_to='icon_pics/', width_field='50')),
                ('body', models.TextField(default=1)),
                ('hunter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
