# Generated by Django 2.1.2 on 2018-11-15 20:20

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='icon_pic',
            field=versatileimagefield.fields.VersatileImageField(upload_to='icon_pics/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_pic',
            field=versatileimagefield.fields.VersatileImageField(upload_to='product_pics/'),
        ),
    ]
